# Generated by Django 4.2.5 on 2023-09-23 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations_account_transaction_record',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
