# Generated by Django 4.2.5 on 2023-09-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_operations_account_transaction_record_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations_account_transaction_record',
            name='account_number_of_reciever',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
