# Generated by Django 4.2.5 on 2023-09-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_operations_account_transaction_record_account_number_of_reciever'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations_account_transaction_record',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
