# Generated by Django 4.2.5 on 2023-10-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_operations_account_transaction_record_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operations_account_transaction_record',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='operations_account_transaction_record',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('INITIALIZED', 'INITIALIZED'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED'), ('RETRYING', 'RETRYING')], max_length=50),
        ),
        migrations.AlterField(
            model_name='operations_account_transaction_record',
            name='transaction_category',
            field=models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='operations_account_transaction_record',
            name='transaction_type',
            field=models.CharField(choices=[('TRANSFER', 'TRANSFER'), ('CASH', 'CASH')], max_length=100),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('INITIALIZED', 'INITIALIZED'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('RECONCILIATION', 'RECONCILIATION')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='taxroll',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('INITIALIZED', 'INITIALIZED'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('RECONCILIATION', 'RECONCILIATION')], max_length=100),
        ),
    ]
