# Generated by Django 4.2.5 on 2023-10-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_operations_account_transaction_record_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Capital_account_transaction_history',
            new_name='Capital_account_transaction_record',
        ),
    ]
