# Generated by Django 4.2.5 on 2023-10-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_rename_capital_account_transaction_history_capital_account_transaction_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='total_amount_for_salary',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_amount_for_tax',
            field=models.BigIntegerField(default=0),
        ),
    ]
