# Generated by Django 4.2.5 on 2023-11-02 07:02

import Main.models.payment_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_alter_payroll_total_amount_for_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='paystack_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='staffs',
            field=models.JSONField(default=Main.models.payment_models.get_default_staffs),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('INITIALIZED', 'INITIALIZED'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('RECONCILIATION', 'RECONCILIATION'), ('CANCELLED', 'CANCELLED'), ('PARTIAL_SUCCESS', 'PARTIAL_SUCCESS')], default='PENDING', max_length=100),
        ),
        migrations.AlterField(
            model_name='taxroll',
            name='staffs',
            field=models.JSONField(default=Main.models.payment_models.get_default_staffs),
        ),
    ]
