# Generated by Django 4.2.5 on 2023-11-02 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Paystack', '0001_initial'),
        ('Main', '0009_staff_paystack_id_alter_payroll_staffs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='staff',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Paystack.bank'),
            preserve_default=False,
        ),
    ]
