# Generated by Django 4.2.5 on 2023-11-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_alter_operations_account_transaction_record_reciever_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations_account_transaction_record',
            name='transaction_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
