# Generated by Django 4.2.5 on 2023-11-12 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_alter_operations_account_transaction_record_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operations_account_transaction_record',
            old_name='reciever_bank',
            new_name='bank',
        ),
    ]
