# Generated by Django 4.2.5 on 2023-11-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_rename_reciever_bank_operations_account_transaction_record_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operations_account_transaction_record',
            old_name='transaction_id',
            new_name='customer_transaction_id',
        ),
        migrations.AddField(
            model_name='operations_account_transaction_record',
            name='reference',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
