# Generated by Django 4.2.5 on 2023-12-02 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_rename_transaction_id_operations_account_transaction_record_customer_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('other_names', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=60)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('FIRST_TERM', 'FIRST_TERM'), ('SECOND_TERM', 'SECOND_TERM'), ('THIRD_TERM', 'THIRD_TERM')], default='FIRST TERM', max_length=50)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Main.school')),
            ],
        ),
    ]
