# Generated by Django 4.2.5 on 2023-12-02 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_class_student_schoolconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('IN DEBT', 'IN DEBT'), ('OUTSTANDING', 'OUTSTANDING')], max_length=50)),
                ('amount_in_debt', models.BigIntegerField(default=0)),
                ('amount_outstanding', models.BigIntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Main.student')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_time_initiated', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('merchant_email', models.EmailField(max_length=254)),
                ('amount_debited', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(max_length=20)),
                ('receipt_id', models.CharField(max_length=20)),
                ('paystack_reference', models.CharField(max_length=50)),
                ('breakdowns', models.JSONField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.student')),
            ],
        ),
    ]
