# Generated by Django 4.2.5 on 2023-12-17 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category_type', models.CharField(choices=[('SCHOOL FEES', 'SCHOOL FEES'), ('BUS FEES', 'BUS FEES'), ('UNIFORM, WEARS AND BOOKS', 'UNIFORM WEARS AND BOOKS'), ('OTHER', 'OTHER')], max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='next_class_to_be_promoted_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.class'),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='academic_session',
            field=models.CharField(choices=[('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025')], default='2020/2021', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('INITIALIZED', 'INITIALIZED'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED'), ('RETRYING', 'RETRYING')], max_length=20),
        ),
        migrations.CreateModel(
            name='UniformAndBooksFeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('is_recommended', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('minimum_percentage', models.BigIntegerField(default=0)),
                ('amount', models.BigIntegerField(default=0)),
                ('is_compoulslry', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.feescategory')),
                ('grades', models.ManyToManyField(to='Main.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolFeesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('term', models.CharField(choices=[('FIRST_TERM', 'FIRST_TERM'), ('SECOND_TERM', 'SECOND_TERM'), ('THIRD_TERM', 'THIRD_TERM')], max_length=50)),
                ('minimum_percentage', models.BigIntegerField(default=0)),
                ('amount', models.BigIntegerField(default=0)),
                ('is_compoulslry', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.feescategory')),
            ],
        ),
        migrations.CreateModel(
            name='OtherFeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('is_compoulslry', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.feescategory')),
                ('grades', models.ManyToManyField(to='Main.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.school')),
            ],
        ),
        migrations.AddField(
            model_name='feescategory',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.class'),
        ),
        migrations.AddField(
            model_name='feescategory',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Main.school'),
        ),
        migrations.CreateModel(
            name='BusFeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('morning_bus_fee', models.BigIntegerField(default=0)),
                ('evening_bus_fee', models.BigIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.feescategory')),
            ],
        ),
    ]
