# Generated by Django 4.2.5 on 2023-12-23 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_feescategory_class_next_class_to_be_promoted_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.school'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SchoolLevyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.BigIntegerField(default=0, null=True)),
                ('amount_in_debt', models.BigIntegerField(default=0, null=True)),
                ('amount_outstanding', models.BigIntegerField(default=0, null=True)),
                ('percentage_paid', models.IntegerField(default=0, null=True)),
                ('percentage_of_student_in_debt', models.IntegerField(default=0, null=True)),
                ('percentage_of_student_outstanding', models.IntegerField(default=0, null=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Main.school')),
            ],
        ),
    ]
