# Generated by Django 4.2.5 on 2023-12-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_class_is_active_paymenthistory_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='amount_paid',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
